version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=subscription_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    container_name: postgres_subscription_service
