server.port: 8082

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  datasource:
    url: jdbc:postgresql://postgres-subscription:5432/subscription_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true

eligibility:
  host: eligibility-service:8081

sales-order:
  host: sales-order-service:8083